school_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from apps.importer.views import generate_importer
from apps.school import models
from apps.school import views
from school_app.views import HomeView
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('api/', include('apps.school.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include("django.contrib.auth.urls")),
    path('students/', generate_importer(models.Student, name="students")),
    path('teachers/', generate_importer(models.Teacher, name="teachers")),
    # path('courses/', generate_importer(models.Course, name="courses")),
    path('courses/', views.scrapper_view, name="courses"),
    path('run_scrapper/', views.run_scrapper_view, name="run_scrapper"),
    path('grades/', generate_importer(models.Grade, name="grades")),
]


handler404 = "school_app.views.page_not_found_view"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/importer/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from django.contrib.auth.models import User

STATUS_CHOICES = (
    ('created', 'Created'),
    ('in_progress', 'In progress'),
    ('success', 'Completed successfully'),
    ('error', 'Finished with error')
)

STEP_CHOICES = (
    ('start_import', 'Starting Import'),
    ('get_import_data', 'Getting data'),
    ('validate_import', 'Validating data'),
    ('create_records', 'Creating Records')
)


class Import(models.Model):
    model_name = models.CharField(max_length=255)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='created')
    step = models.CharField(max_length=20, choices=STEP_CHOICES, null=True, blank=True)
    start_date = models.DateTimeField(auto_now_add=True)
    end_date = models.DateTimeField(null=True, blank=True)
    total_lines = models.IntegerField(null=True, blank=True)
    imported_lines = models.IntegerField(null=True, blank=True, default=0)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    imported_data = models.JSONField(null=True, blank=True)
    task_id = models.CharField(max_length=50, null=True, blank=True)
    document = models.FileField(
        upload_to='documents/',
        validators=[FileExtensionValidator(allowed_extensions=['csv', 'xls', 'xlsx'])],
        null=True,
        blank=True
    )

    def __str__(self):
        return f"Import {self.model_name} - {self.get_status_display()}"

apps/importer/forms.py
from django import forms
from .models import Import


class ImportForm(forms.ModelForm):
    class Meta:
        model = Import
        fields = ['document']

    def __init__(self, *args, **kwargs):
        super(ImportForm, self).__init__(*args, **kwargs)
        self.fields['document'].required = True

apps/importer/views.py
import pandas as pd
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.views.generic import RedirectView
from .forms import ImportForm
from .models import Import


def generate_importer(model, name=None):
    @login_required
    def importer_view(request):
        """
        View function for the importer page.

        Handles the importing of data for a specific model.

        Args:
            request (HttpRequest): The HTTP request object.

        Returns:
            HttpResponse: The HTTP response object rendering the importer.html template.
        """
        if request.method == 'POST':
            form = ImportForm(request.POST, request.FILES)
            if form.is_valid():
                import_instance = form.save(commit=False)
                import_instance.model_name = model._meta.label
                import_instance.created_by = request.user
                import_instance.save()

                return HttpResponseRedirect(request.path_info)
        else:
            form = ImportForm()

        imports = Import.objects.filter(created_by=request.user, model_name=model._meta.label).order_by('id')

        return render(request, 'importer.html', {
            'form': form,
            'imports': imports,
            'model_name': model.__name__,
            'namespace': name
        })

    def import_view(request, import_id):
        """
        View function for the import detail page.

        Displays the imported data for a specific import instance.

        Args:
            request (HttpRequest): The HTTP request object.
            import_id (int): The ID of the Import object.

        Returns:
            HttpResponse: The HTTP response object rendering the import.html template.
        """
        import_instance = Import.objects.get(id=import_id)

        valids = []
        invalids = []
        file_error = ''
        creation_error = ''

        if import_instance.imported_data is not None:
            valids = import_instance.imported_data.get('valids', [])
            invalids = import_instance.imported_data.get('invalids', [])
            file_error = import_instance.imported_data.get('file_error', '')
            creation_error = import_instance.imported_data.get('creation_error', '')

        return render(request, 'import.html', {
            'instance': import_instance,
            'namespace': name,
            'valids': valids,
            'invalids': invalids,
            'file_error': file_error,
            'creation_error': creation_error
        })

    def check_import(request, import_id):
        """
        View function to check the status of an import.

        Returns the status and step of the import as a JSON response.

        Args:
            request (HttpRequest): The HTTP request object.
            import_id (int): The ID of the Import object.

        Returns:
            JsonResponse: The JSON response object containing the import status and step.
        """
        import_instance = Import.objects.get(id=import_id)

        data = {
            'status': import_instance.status,
            'step': import_instance.step
        }

        return JsonResponse(data)

    def export_fields_to_xls(request):
        """
        View function that exports the model's fields to an Excel file.

        Args:
            request (HttpRequest): The HTTP request object.

        Returns:
            HttpResponse: The HTTP response object containing the generated Excel file.
        """
        # Get the model's fields
        model_fields = [
            field.name
            for field in model._meta.fields
            if field.name != 'id' and not field.auto_created and not (
                    getattr(field, 'auto_now', False) or getattr(field, 'auto_now_add', False))
        ]

        # Create an empty DataFrame with the specified columns
        df = pd.DataFrame(columns=model_fields)

        # Check if fields_to_map attribute exists in the model
        if hasattr(model, 'fields_to_map') and isinstance(model.fields_to_map, dict):
            # Iterate over the fields_to_map dictionary
            for field_name, related_field in model.fields_to_map.items():
                if field_name in model_fields:
                    # Get the related field value using getattr
                    related_value = getattr(model, related_field)
                    # Assign the related field value to the DataFrame column
                    df[field_name] = related_value

        # # Assign the remaining model fields to the DataFrame
        # for field_name in model_fields:
        #     if field_name not in df.columns:
        #         df[field_name] = getattr(model, field_name)

        # Create an Excel writer using the HttpResponse object
        output = HttpResponse(content_type='application/vnd.ms-excel')
        output['Content-Disposition'] = 'attachment; filename=Import_{}.xls'.format(model.__name__)

        # Create an Excel writer using xlwt engine
        writer = pd.ExcelWriter(output)

        # Write the DataFrame to the Excel file
        df.to_excel(writer, index=False, sheet_name='Sheet1')

        # Close the writer without saving the Excel file
        writer.close()

        return output

    def export_fields_to_xls2(request):
        """
        View function that exports the model's fields to an Excel file.

        Args:
            request (HttpRequest): The HTTP request object.

        Returns:
            HttpResponse: The HTTP response object containing the generated Excel file.
        """
        # Get the model's fields
        model_fields = [
            field.name
            for field in model._meta.fields
            if field.name != 'id' and not field.auto_created and not (
                    getattr(field, 'auto_now', False) or getattr(field, 'auto_now_add', False))
        ]

        # Create an empty DataFrame
        df = pd.DataFrame(columns=model_fields)

        # Check if fields_to_map attribute exists in the model
        if hasattr(model, 'fields_to_map') and isinstance(model.fields_to_map, dict):
            # Iterate over the model instances
            instances = model.objects.all()
            for instance in instances:
                row = {}
                # Iterate over the fields_to_map dictionary
                for field_name, related_field in model.fields_to_map.items():
                    if field_name in model_fields:
                        field_value = getattr(instance, field_name)
                        # Get the related field value using getattr
                        related_value = getattr(field_value, related_field)

                        if callable(related_value):
                            related_value = related_value()

                        if not isinstance(related_value, str):
                            related_value = ''

                        # Assign the related field value to the row dictionary
                        row[field_name] = related_value

                # Assign the remaining model fields to the row dictionary
                for field_name in model_fields:
                    if field_name not in row and field_name != 'fields_to_map':
                        row[field_name] = getattr(instance, field_name)

                # Append the row dictionary to the DataFrame
                df = df.append(row, ignore_index=True)

        # Create an Excel writer using the HttpResponse object
        output = HttpResponse(content_type='application/vnd.ms-excel')
        output['Content-Disposition'] = 'attachment; filename=Import_{}.xls'.format(model.__name__)

        # Create an Excel writer using xlwt engine
        writer = pd.ExcelWriter(output)

        # Write the DataFrame to the Excel file
        df.to_excel(writer, index=False, sheet_name='Sheet1')

        # Close the writer without saving the Excel file
        writer.close()

        return output

    urlpatterns = [
        path("", RedirectView.as_view(url='importer/', permanent=False)),
        path("importer/", importer_view, name="importer"),
        path("import/<int:import_id>/", import_view, name="import"),
        path('import/<int:import_id>/status/', check_import, name='check_import'),
        path('importer/file', export_fields_to_xls2, name="importer_file"),
    ]

    return include((urlpatterns, name), namespace=name)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'general.css' %}">
    <link rel="stylesheet" href="{% static 'theme.css' %}">
    <script>
        (() => {
            const html_tag = document.documentElement;
            if (!html_tag.classList.contains('dark') && !html_tag.classList.contains('light'))
            {
                let theme = localStorage.getItem('theme');
                if (!theme)
                {
                    theme = 'dark'
                    localStorage.setItem('theme', theme)
                }
                html_tag.classList.add(theme)
            }
        })()
    </script>
    {% block head %}{% endblock %}
</head>

<body>
    {% block content %}{% endblock %}
</body>

</html>

templates/home.html
{% extends 'internal.html' %}
{% load importer_extras %}

{% block internal_content %}
<div class="container center w100">
    <div style="flex: auto; max-width: 1200px">
        <ul class="dashboard">
            <li>
                <a href="/students/">
                    <div class="mso">person</div>
                    <br/>
                    Students Importer
                </a>
            </li>
            <li>
                <a href="/teachers/">
                    <span class="mso">school</span>
                    <br/>
                    Teachers Importer
                </a>
            </li>
            <li>
                <a href="/courses/">
                    <span class="mso">groups</span>
                    <br/>
                    Courses
                </a>
            </li>
            <li>
                <a href="/grades/">
                    <span class="mso">checklist</span>
                    <br/>
                    Grades Importer
                </a>
            </li>
            <li>
                <a href="/api/">
                    <span class="mso">api</span>
                    <br/>
                    School <br/>
                    Rest API
                </a>
            </li>
        </ul>
    </div>
</div>
{% endblock %}}

templates/import.html
{% extends 'internal.html' %}
{% load static %}
{% load importer_extras %}

{% block internal_content %}
<div style="margin: 1rem 0">
    <a class="btn small primary mso" href="{% url namespace|urlc:'importer' %}">arrow_back</a>
    <span class="primary-text" style="font-size: 2em; margin-left: 1rem">
        Import started on {{ instance.start_date}}
    </span>
</div>
<div class="container start w100 h100">
    <div class="box surface-container" style="min-width: 360px">
        <table class="t2">
            <tbody>
                <tr>
                    <td><b>Status:</b></td>
                    <td>
                        <span class="box primary {instance.status}" style="padding: 4px">
                            {{ instance.get_status_display }}
                        </span>
                    </td>
                </tr>
                <tr>
                    <td><b>Step:</b></td>
                    <td>{{ instance.get_step_display }}</td>
                </tr>
                <tr>
                    <td><b>Model:</b></td>
                    <td>{{ instance.model_name }}</td>
                </tr>
                <tr>
                    <td><b>Create by:</b>
                    <td>{{ instance.created_by }}</td>
                </tr>
                <tr>
                    <td><b>Start Date:</b></td>
                    <td>{{ instance.start_date }}</td>
                </tr>
                <tr>
                    <td><b>End Date:</b></td>
                    <td>{% if instance.end_date is not None %}{{ instance.end_date }}{% else %}-{% endif %}</td>
                </tr>
                <tr>
                    <td><b>Total lines:</b></td>
                    <td>{% if instance.total_lines is not None %}{{ instance.total_lines }}{% else %}-{% endif %}</td>
                </tr>
                <tr>
                    <td><b>Imported lines:</b>
                    <td>{{ instance.imported_lines }}</td>
                </tr>
                <tr>
                    <td><b>Task ID:</b>
                    <td>{% if instance.task_id is not None %}{{ instance.task_id }}{% else %}-{% endif %}</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="w100 box surface-container" style="flex: auto">
        {% if instance.status == "in_progress" %}
        <p>This page will automatically reload every 3 seconds while the import is in progress.</p>
        {% endif %}
        <script>
            (() => {
                setTimeout(reload, 3000)

                function reload() {
                    fetch('{% url namespace|urlc:'check_import' import_id=instance.id %}')
                        .then(function (response) {
                            if (response.status === 200)
                                return response.json();
                            else
                                console.log('Error al consultar el estado de importación');

                        })
                        .then(function (data) {
                            if (data.status === "in_progress" || data.status === "created")
                                location.reload();
                            else
                                console.log('El estado de importación no es "in_progress". No se recargará la página.');
                        })
                        .catch(function (error) {
                            console.log('Error de red:', error);
                        });
                }
            })();
        </script>
        {% if valids %}
        <div>
            <h3>Valid rows:</h3>
            <table class="table">
                <thead>
                    <tr>
                        <th>row</th>
                        {% for key, value in valids.0.data.items %}
                        <td>{{ key }}</td>
                        {% endfor %}
                    </tr>
                </thead>
                <tbody>
                    {% for valid in valids %}
                    <tr>
                        <td>{{ valid.order }}</td>
                        {% for key, value in valid.data.items %}
                        <td>{{ value }}</td>
                        {% endfor %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% endif %}
        {% if invalids %}
        <div>
            <h3>Invalid rows:</h3>
            <table class="table">
                <thead>
                    <tr>
                        <th>Row</th>
                        <th>Data</th>
                    </tr>
                </thead>
                <tbody>
                    {% for invalid in invalids %}
                    <tr>
                        <td>{{ invalid.order }}</td>
                        <td class="x">
                            <div>
                                <table class="table">
                                    <thead>
                                        <tr>

                                            {% for key, value in invalids.0.data.items %}
                                            <td>{{ key }}</td>
                                            {% endfor %}
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>

                                            {% for key, value in invalid.data.items %}
                                            <td>{{ value }}</td>
                                            {% endfor %}
                                        </tr>
                                    </tbody>
                                </table>

                            </div>
                            <div class="wrap-collabsible">
                                <input id="collapsible-{{ invalid.order }}" class="toggle" type="checkbox">
                                <label for="collapsible-{{ invalid.order }}" class="lbl-toggle">errors</label>
                                <div class="collapsible-content">
                                    <div class="content-inner">
                                        <ul class="list w100">
                                            {% for key, value in invalid.errors.items %}
                                            <li class="item"><b>{{ key }}:</b> <span class="content">{{ value }}</span>
                                            </li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                            </div>

                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% endif %}
        {% if file_error %}
        <h3>File Error</h3>
        <pre>{{ file_error }}</pre>
        {% endif %}
        {% if creation_error %}
        <h3>Creation Error</h3>
        <pre>{{ creation_error }}</pre>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/importer.html
{% extends 'internal.html' %}
{% load static %}
{% load importer_extras %}

{% block internal_content %}
<div style="margin: 1rem 0">
    <a class="btn small primary mso" href="{% url 'home' %}">arrow_back</a>
    <span class="primary-text" style="font-size: 2em; margin-left: 1rem">{{ model_name }} Imports</span>
</div>
<div class="container start w100 h100">
  <div class="container col center w100 box surface-container" style="flex: auto">
    {% if documents.count == 0 %}
    <span>No Imports found</span>
    <img src="{% static 'No data-cuate.png' %}" alt="No Data" width="360px" />
    {% else %}
    <table class="table">
      <thead>
        <tr>
          <th>ID</th>
          <th>Status</th>
          <th>Step</th>
          <th>Start Date</th>
          <th>End Date</th>
          <th>Total lines</th>
          <th>Imported lines</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for import_instance in imports %}
        <tr>
          <td>{{ import_instance.id }}</td>
          <td>{{ import_instance.get_status_display }}</td>
          <td>{{ import_instance.get_step_display }}</td>
          <td>{{ import_instance.start_date }}</td>
          <td>{% if import_instance.end_date is not None %}{{ import_instance.end_date }}{% else %}-{% endif %}</td>
          <td>{% if import_instance.total_lines is not None %}{{ import_instance.total_lines }}{% else %}-{% endif %}</td>
          <td>{{ import_instance.imported_lines }}</td>
          <td>
            <a class="btn primary small mso"
              href="{% url namespace|urlc:'import' import_id=import_instance.id %}">search</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% endif %}
  </div>
  <div class="container col" style="min-width: 360px">
    <div class="box surface-container">
      Importer template <a href="{% url namespace|urlc:'importer_file' %}">Importer {{ model_name }}</a>
    </div>
    <form method="post" enctype="multipart/form-data" class="box surface-container">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="w100 primary">Upload</button>
    </form>
  </div>
</div>
{% endblock %}

templates/internal.html
{% extends 'base.html' %}

{% block head %}
<script>
    function on_change_theme (evn)
    {
        const html_tag = document.documentElement;
        const btn = document.getElementById('change-theme')

        if (html_tag.classList.contains("dark")) {
            html_tag.classList.remove("dark");
            html_tag.classList.add("light");
            btn.textContent = "dark_mode";
            localStorage.setItem('theme', 'light');
        }
        else if (html_tag.classList.contains("light"))
        {
            html_tag.classList.remove("light");
            html_tag.classList.add("dark");
            btn.textContent = "light_mode";
            localStorage.setItem('theme', 'dark');
        }
    }
</script>
{% endblock %}
{% block content %}
<header>
    <a href="/" class="logo">School App</a>
    <div style="flex: auto"></div>
    <span>Hi {{ user.username }}!</span>
    <a href="{% url 'admin:index' %}" class="btn on-primary">Admin</a>
    <a href="{% url 'logout' %}" class="btn on-primary">Sign out</a>
    <button id="change-theme" class="on-primary small mso" onclick="on_change_theme()">light_mode</button>
</header>
<main class="container col" style="margin: 0 auto">
    {% block internal_content %}{% endblock %}
</main>
{% endblock %}

templates/scrapper.html
{% extends 'internal.html' %}
{% load static %}
{% load importer_extras %}

{% block internal_content %}
<div style="margin: 1rem 0">
    <a class="btn small primary mso" href="{% url 'home' %}">arrow_back</a>
    <span class="primary-text" style="font-size: 2em; margin-left: 1rem">
        Import started on {{ instance.start_date}}
    </span>
</div>
<div class="container start w100 h100">
    <div class="box surface-container" style="min-width: 360px">
        <h1>Tabla de Cursos</h1>
        <a href="#" class="btn primary" id="execute-task">Run scrapper</a>
    <div id="message-container" style="margin: 1rem"></div>
    {% csrf_token %}
   <script>
       function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        document.getElementById('execute-task').addEventListener('click', function(e) {
            e.preventDefault();  // Prevent default redirection

            const csrftoken = getCookie('csrftoken');

            fetch("{% url 'run_scrapper' %}", {
                method: "POST",
                headers: {
                    "X-Requested-With": "XMLHttpRequest",  // Indicates AJAX request
                    "X-CSRFToken": csrftoken  // Include CSRF token in request headers
                }
            })
            .then(function(response) {
                if (response.ok) {
                    if (response.status === 200) {
                        response.text().then(function(message) {
                            console.log(message);
                            document.getElementById('message-container').textContent = message;
                        });
                    } else {
                        console.error("Error executing asynchronous task");
                        // Handle task error here if needed
                    }
                } else {
                    console.error("Error executing asynchronous task");
                    // Handle task error here if needed
                }
            })
            .catch(function(error) {
                console.error("Error executing asynchronous task", error);
                // Handle task error here if needed
            });
        });
    </script>
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Descripción</th>
            </tr>
        </thead>
        <tbody>
            {% for course in courses %}
            <tr>
                <td>{{ course.id }}</td>
                <td>{{ course.name }}</td>
                <td>{{ course.description }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    </div>
</div>
{% endblock %}